DenizAyakkabi/DenizAyakkabi/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DenizAyakkabi.Controllers
{
    public class AboutController : Controller
    {
        AboutManager am = new AboutManager(new EFAboutDal());
        AboutValidation av = new AboutValidation();
        public ActionResult MainAbout()
        {
            var x = am.List();
            return View(x);
        }
        [HttpGet]
        public ActionResult UpdateAbout(int id)
        {
            var b = am.GetByID(id);
            return View(b);
        }
        [HttpPost]
        public ActionResult UpdateAbout(About a, HttpPostedFileBase dosya)
        {
            ValidationResult vr = av.Validate(a);
            if (vr.IsValid)
            {
                if (dosya != null && dosya.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Images/"), dosya.FileName);
                    dosya.SaveAs(path);
                    a.Image = dosya.FileName;
                    am.TUpdate(a);
                }
                return RedirectToAction("MainProduct");
            }
            else
            {
                foreach (var item in vr.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

DenizAyakkabi/DenizAyakkabi/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DenizAyakkabi.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EFCategoryDal());
        CategoryValidation cv = new CategoryValidation();
        public ActionResult MainCategory()
        {
            var x = cm.List();
            return View(x);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category c)
        {
            ValidationResult vr = cv.Validate(c);
            if (vr.IsValid)
            {
                cm.TAdd(c);
                return RedirectToAction("MainCategory");
            }
            else
            {
                foreach (var item in vr.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult DeleteCategory(int id)
        {
            var x = cm.GetByID(id);
            cm.TDelete(x);
            return RedirectToAction("MainCategory");
        }


        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {
            var x = cm.GetByID(id);
            return View(x);
        }
        [HttpPost]
        public ActionResult UpdateCategory(Category c)
        {
            ValidationResult vr = cv.Validate(c);
            if (vr.IsValid)
            {
                cm.TUpdate(c);
                return RedirectToAction("MainCategory");
            }
            else
            {
                foreach (var item in vr.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

DenizAyakkabi/DenizAyakkabi/Controllers/ContactController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DenizAyakkabi.Controllers
{
    public class ContactController : Controller
    {
        ContactManager cm = new ContactManager(new EFContactDal());
        public ActionResult MainContact()
        {
            var x = cm.List();
            return View(x);
        }
        public ActionResult DeleteContact(int id)
        {
            var x = cm.GetByID(id);
            cm.TDelete(x);
            return RedirectToAction("MainContact");
        }

        public ActionResult ViewContact(int id)
        {
            var x = cm.GetByID(id);
            return View(x);
        }
    }
}

DenizAyakkabi/DenizAyakkabi/Controllers/MainPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DenizAyakkabi.Controllers
{
    public class MainPageController : Controller
    {
        // GET: MainPage
        public ActionResult MainPage()
        {
            return View();
        }

        public ActionResult Product()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

DenizAyakkabi/DenizAyakkabi/Controllers/ProductController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DenizAyakkabi.Controllers
{
    public class ProductController : Controller
    {
        ProductManager pm = new ProductManager(new EFProductDal());
        ProductValidation pv = new ProductValidation();
        SubCategoryManager sm = new SubCategoryManager(new EFSubCategoryDal());
        public ActionResult MainProduct()
        {
            var x = pm.List();
            return View(x);
        }
        public ActionResult DeleteProduct(int id)
        {
            var x = pm.GetByID(id);
            pm.TDelete(x);
            return RedirectToAction("MainProduct");
        }
        [HttpGet]
        public ActionResult AddProduct()
        {
            List<SelectListItem> subc = (from x in sm.List() select new SelectListItem { Text = x.SubCategoryName1, Value = x.SubCategoryID.ToString() }).ToList();
            ViewBag.dgr = subc;
            return View();
        }
        [HttpPost]
        public ActionResult AddProduct(Product p, HttpPostedFileBase dosya)
        {
            ValidationResult vr = pv.Validate(p);
            if (vr.IsValid)
            {
                if (dosya != null && dosya.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Images/"), dosya.FileName);
                    dosya.SaveAs(path);
                    p.Image = dosya.FileName;
                    pm.TAdd(p);
                }
                return RedirectToAction("MainProduct");
            }
            else
            {
                foreach (var item in vr.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult UpdateProduct(int id)
        {
            List<SelectListItem> subc = (from x in sm.List() select new SelectListItem { Text = x.SubCategoryName1, Value = x.SubCategoryID.ToString() }).ToList();
            ViewBag.dgr = subc;
            var r = pm.GetByID(id);
            return View(r);
        }
        [HttpPost]
        public ActionResult UpdateProduct(Product p, HttpPostedFileBase dosya)
        {
            ValidationResult vr = pv.Validate(p);
            if (vr.IsValid)
            {
                if (dosya != null && dosya.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Images/"), dosya.FileName);
                    dosya.SaveAs(path);
                    p.Image = dosya.FileName;
                    pm.TUpdate(p);
                }
                return RedirectToAction("MainProduct");
            }
            else
            {
                foreach (var item in vr.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

DenizAyakkabi/DenizAyakkabi/Views/About/MainAbout.cshtml
@using EntityLayer.Concrete
@model List<About>
@{
    ViewBag.Title = "MainAbout";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h3 style="margin-left:15px">HAKKIMIZDA BILGILERI</h3>
<br />
<table class="table table-hover" style="margin-left:15px">
    <tr>
        <th>ID</th>
        <th>Açıklama 1</th>
        <th>Açıklama 2</th>
        <th>Başlık 1</th>
        <th>Başlık 2</th>
        <th>Başlık 3</th>
        <th>Başlık 4</th>
        <th>Başlık 5</th>
        <th>Düzenle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.AboutID
            </td>
            <td>
                @item.Description
            </td>
            <td>
                @item.Description2
            </td>
            <td>
                @item.Title1
            </td>
            <td>
                @item.Title2
            </td>
            <td>
                @item.Title3
            </td>
            <td>
                @item.Title4
            </td>
            <td>
                @item.Title5
            </td>
            <td>
                <a href="~/About/UpdateAbout/@item.AboutID" class="btn btn-warning">Düzenle</a>

            </td>
        </tr>
    }
</table>

DenizAyakkabi/DenizAyakkabi/Views/About/UpdateAbout.cshtml
@model EntityLayer.Concrete.About
@{
    ViewBag.Title = "UpdateAbout";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<br />
<h2 style="margin-left:15px">Hakkımızda Düzenleme Sayfası</h2>
<br />
@using (Html.BeginForm("UpdateAbout", "About", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div style="margin-left:15px" class="form-group">
    @Html.Label("ID")
    @Html.TextBoxFor(n => n.AboutID, new { @class = "form-control" })
    <br />
    <br />
    @Html.Label("Açıklama 1")
    @Html.TextBoxFor(n => n.Description, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Description)
    <br />
    <br />
    @Html.Label("Açıklama 2")
    @Html.TextBoxFor(n => n.Description2, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Description2)
    <br />
    <br />
    @Html.Label("Başlık 1")
    @Html.TextBoxFor(n => n.Title1, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Title1)
    <br />
    <br />
    @Html.Label("Başlık 2")
    @Html.TextBoxFor(n => n.Title2, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Title2)
    <br />
    <br />
    @Html.Label("Başlık 3")
    @Html.TextBoxFor(n => n.Title3, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Title3)
    <br />
    <br />
    @Html.Label("Başlık 4")
    @Html.TextBoxFor(n => n.Title4, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Title4)
    <br />
    <br />
    @Html.Label("Başlık 5")
    @Html.TextBoxFor(n => n.Title5, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Title5)
    <br />
    <br />
    <input class="form-control" type="file" name="dosya" />
    <br />
    <br />
    <button class="btn btn-primary">Kaydet</button>
</div>
}

DenizAyakkabi/DenizAyakkabi/Views/Category/AddCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<br />
<h2 style="margin-left:15px">Yeni Kategori Ekleme Sayfası</h2>
<br />
@using (Html.BeginForm("AddCategory", "Category", FormMethod.Post))
{

    <div style="margin-left:15px" class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(n => n.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(n => n.CategoryName)
        <br />
        <br />
        <button style="margin-left:15px" class="btn btn-primary">Yeni Kategori Ekle</button>
    </div>
}

DenizAyakkabi/DenizAyakkabi/Views/Category/MainCategory.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "MainCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3 style="margin-left:15px">KATEGORİ LİSTESİ</h3>
<br />
<table class="table table-hover"style="margin-left:15px">

    <tr>
        <th>ID</th>
        <th>Kategori</th>
        <th>Sil</th>
        <th>Düzenle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.CategoryID
            </td>
            <td>
                @item.CategoryName
            </td>
            <td>
                <a href="~/Category/DeleteCategory/@item.CategoryID" class="btn btn-danger">Sil</a>

            </td>
            <td>
                <a href="~/Category/UpdateCategory/@item.CategoryID" class="btn btn-warning">Düzenle</a>

            </td>
        </tr>
    }
</table>
<a href="~/Category/AddCategory" style="margin-left:15px" class="btn btn-primary">Yeni Kategori Ekle</a>

DenizAyakkabi/DenizAyakkabi/Views/Category/UpdateCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<br />
<h2 style="margin-left:15px">Kategori Düzenleme Sayfası</h2>
<br />
@using (Html.BeginForm("UpdateCategory", "Category", FormMethod.Post))
{
    <div style="margin-left:15px" class="form-group">
        @Html.Label("Kategori ID")
        @Html.TextBoxFor(n => n.CategoryID, new { @class = "form-control" })
        <br />
        <br />
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(n => n.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(n => n.CategoryName)
        <br />
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

DenizAyakkabi/DenizAyakkabi/Views/Contact/MainContact.cshtml
@using EntityLayer.Concrete
@model List<Contact>
@{
    ViewBag.Title = "MainContact";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3 style="margin-left:15px">ILETISIM LİSTESİ</h3>
<br />
<table class="table table-hover" style="margin-left:15px">

    <tr>
        <th>ID</th>
        <th>Gönderen</th>
        <th>Email</th>
        <th>Konu</th>
        <th>Mesaj</th>
        <th>Sil</th>
        <th>Görüntüle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.ContactID
            </td>
            <td>
                @item.FullName
            </td>
            <td>
                @item.Email
            </td>
            <td>
                @item.Subject
            </td>
            <td>
                @item.Message
            </td>
            <td>
                <a href="~/Contact/DeleteContact/@item.ContactID" class="btn btn-danger">Sil</a>
            </td>
            <td>
                <a href="~/Contact/ViewContact/@item.ContactID" class="btn btn-warning">Görüntüle</a>

            </td>
        </tr>
    }
</table>

DenizAyakkabi/DenizAyakkabi/Views/Contact/ViewContact.cshtml
@model EntityLayer.Concrete.Contact 
@{
    ViewBag.Title = "ViewContact";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h3 style="margin-left:15px">ILETISIM BİLGİLERİ</h3>
<br />
<div style="margin-left:15px" class="form-group">
    @Html.Label("ID")
    @Html.TextBoxFor(n => n.ContactID, new { @class = "form-control" })
    <br />
    <br />
    @Html.Label("Gönderen")
    @Html.TextBoxFor(n => n.FullName, new { @class = "form-control" })
    <br />
    <br />
    @Html.Label("Email")
    @Html.TextBoxFor(n => n.Email, new { @class = "form-control" })
    <br />
    <br />
    @Html.Label("Konu")
    @Html.TextBoxFor(n => n.Subject, new { @class = "form-control" })
    <br />
    <br />
    @Html.Label("Mesaj")
    @Html.TextAreaFor(n => n.Message, new { @class = "form-control" })
    <br />
    <br />
</div>

DenizAyakkabi/DenizAyakkabi/Views/MainPage/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main-container">
    <main>
        <div class="page-banner container-fluid no-padding">
            <div class="container">
                <div class="banner-content">
                    <h3>Bizimle İletişime Geçin</h3>
                    <p>our vision is to be Earth's most customer centric company</p>
                </div>
                <ol class="breadcrumb">
                    <li><a href="~/MainPage/MainPage" title="Home">Ana Sayfa</a></li>
                    <li class="active">Iletisim</li>
                </ol>
            </div>
        </div>
        <div class="contact-us container-fluid no-padding">
            <div class="col-md-6 col-sm-6 col-xs-12 no-padding">
                <div class="contact-detail">
                    <div class="section-header">
                        <h3>Get In Touch</h3>
                        <p>Also Connect With Social Media To Anytime</p>
                    </div>
                    <div class="contact-info">
                        <i class="icon icon-Pointer"></i>
                        <p>Max Shop, 65 Huge Street Melbourne,</p>
                        <p>2850 Australia.</p>
                    </div>
                    <div class="contact-info">
                        <i class="icon icon-Phone2"></i>
                        <a href="tel:(11)1234567890" title="Phone" class="phone">(11) 123 456 7890</a>
                    </div>
                    <div class="contact-info">
                        <i class="icon icon-Phone2"></i>
                        <a href="mailto:info@maxshop.com" title="info@maxshop.com">info@maxshop.com</a>
                    </div>
                    <ul class="social">
                        <li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#" title="Tumblr"><i class="fa fa-tumblr"></i></a></li>
                        <li><a href="#" title="Vimeo"><i class="fa fa-vimeo"></i></a></li>
                        <li><a href="#" title="Pinterest"><i class="fa fa-pinterest-p"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 no-padding">
                <div class="form-detail">
                    <div class="section-header">
                        <h3>Send a Message</h3>
                        <p>Feel Free To Say Everything And Ask Questions</p>
                    </div>
                    <form>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                            <input type="text" name="contact-name" class="form-control" id="input_name" placeholder="Full Name *" required />
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                            <input type="text" name="contact-email" class="form-control" id="input_email" placeholder="Email Address *" required />
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                            <input type="text" required="" placeholder="Subject *" id="input_subject" class="form-control" name="contact-subject">
                        </div>
                        <div class="form-group col-md-12 col-sm-12 col-xs-12">
                            <textarea placeholder="Type Your Message . . ." id="textarea_message" name="contact-message" rows="5" class="form-control"></textarea>
                        </div>
                        <div class="form-group col-md-12 col-sm-12 col-xs-12">
                            <button title="Submit" type="submit" id="btn_submit" name="post">Send Message</button>
                        </div>
                        <div id="alert-msg" class="alert-msg"></div>
                    </form>
                </div>
            </div>
            <div class="map container-fluid no-padding">
                <div class="map-canvas" id="map-canvas-contact" data-lat="-32.559356" data-lng="149.564237" data-string="Max Shop, 65 Huge Street Melbourne,  2850 Australia." data-zoom="12"></div>
                <a href="#">Max <span>Shop</span></a>
            </div>
        </div>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDW40y4kdsjsz714OVTvrw7woVCpD8EbLE"></script>
    </main>
</div>

DenizAyakkabi/DenizAyakkabi/Views/Product/AddProduct.cshtml
@model EntityLayer.Concrete.Product
@{
    ViewBag.Title = "AddProduct";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<br />
<h2 style="margin-left:15px">Yeni Ürün Ekleme Sayfası</h2>
<br />
@using (Html.BeginForm("AddProduct", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div style="margin-left:15px" class="form-group">
        @Html.Label("Ürün Adı")
        @Html.TextBoxFor(n => n.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(n => n.Title)
        <br />
        <br />
        @Html.Label("Ürün Açıklaması")
        @Html.TextBoxFor(n => n.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(n => n.Description)
        <br />
        <br />
        @Html.Label("Ürün Fiyatı")
        @Html.TextBoxFor(n => n.Price, new { @class = "form-control" })
        @Html.ValidationMessageFor(n => n.Price)
        <br />
        <br />
        @Html.Label("Ürün Adeti")
        @Html.TextBoxFor(n => n.Quantity, new { @class = "form-control" })
        @Html.ValidationMessageFor(n => n.Quantity)
        <br />
        <br />
        @Html.Label("Ürün Alt Kategorisi")
        @Html.DropDownListFor(n => n.SubCategory, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
        <br />
        <br />
        <input class="form-control" type="file" name="dosya" />
        <br />
        <br />

        <button class="btn btn-primary">Yeni Ürün Ekle</button>
    </div>
}

DenizAyakkabi/DenizAyakkabi/Views/Product/MainProduct.cshtml
@using EntityLayer.Concrete
@model List<Product>
@{
    ViewBag.Title = "MainProduct";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h3 style="margin-left:15px">ÜRÜN LİSTESİ</h3>
<br />
<table style="margin-left:15px" class="table table-hover">

    <tr>
        <th>ID</th>
        <th>Baslık</th>
        <th>Acıklama</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Resim</th>
        <th>Sil</th>
        <th>Düzenle</th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>
        @item.ProductID
    </td>
    <td>
        @item.Title
    </td>
    <td>
        @item.Description
    </td>
    <td>
        @item.Price
    </td>
    <td>
        @item.Quantity
    </td>
    <td>
        <img src="Images/@item.Image" height="70" width="90" alt="Images/@item.Image">
    </td>
    <td>
        <a href="~/Product/DeleteProduct/@item.ProductID" class="btn btn-danger">Sil</a>

    </td>
    <td>
        <a href="~/Product/UpdateProduct/@item.ProductID" class="btn btn-warning">Düzenle</a>

    </td>
</tr>
    }
</table>
<a href="~/Product/AddProduct" style="margin-left:15px" class="btn btn-primary">Yeni Ürün Ekle</a>

DenizAyakkabi/DenizAyakkabi/Views/Product/UpdateProduct.cshtml
@model EntityLayer.Concrete.Product
@{
    ViewBag.Title = "UpdateProduct";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<br />
<h2 style="margin-left:15px">Ürün Düzenleme Sayfası</h2>
<br />
@using (Html.BeginForm("UpdateProduct", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

<div style="margin-left:15px" class="form-group">
    @Html.Label("ID")
    @Html.TextBoxFor(n => n.ProductID, new { @class = "form-control" })
    <br />
    <br />
    @Html.Label("Ürün Adı")
    @Html.TextBoxFor(n => n.Title, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Title)
    <br />
    <br />
    @Html.Label("Ürün Açıklaması")
    @Html.TextBoxFor(n => n.Description, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Description)
    <br />
    <br />
    @Html.Label("Ürün Fiyatı")
    @Html.TextBoxFor(n => n.Price, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Price)
    <br />
    <br />
    @Html.Label("Ürün Adeti")
    @Html.TextBoxFor(n => n.Quantity, new { @class = "form-control" })
    @Html.ValidationMessageFor(n => n.Quantity)
    <br />
    <br />
    @Html.Label("Ürün Alt Kategorisi")
    @Html.DropDownListFor(n => n.SubCategory, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
    <br />
    <br />
    <input class="form-control" type="file" name="file" />
    <br />
    <br />
    <button class="btn btn-primary">Kaydet</button>
</div>
}